In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.preprocessing as skl_pre
import sklearn.linear_model as skl_lm
import sklearn.discriminant_analysis as skl_da
import sklearn.neighbors as skl_nb
plt.style.use('seaborn-white')

In [14]:
#Importing songs for project
#songs to classify
songs_to_classify = pd.read_csv('http://www.it.uu.se/edu/course/homepage/sml/project/songs_to_classify.csv')
#training data
training_data = pd.read_csv('http://www.it.uu.se/edu/course/homepage/sml/project/training_data.csv')

In [15]:
#Divide set into training and testing randomly, sampling indices for training
# Size of test set
size = 300

trainI = np.random.choice(training_data.shape[0], size, replace=False)
trainIndex = training_data.index.isin(trainI)
train = training_data.iloc[trainIndex] # training set
test = training_data.iloc[~trainIndex] # test set

In [32]:
#Use LDA model
model_lda = skl_da.LinearDiscriminantAnalysis()
X_train = train[['acousticness','danceability', 'loudness','instrumentalness','key','liveness',
                'mode','speechiness','tempo','time_signature','valence','label']]
Y_train = train['label']
X_test = test[['acousticness','danceability', 'loudness','instrumentalness','key','liveness',
                'mode','speechiness','tempo','time_signature','valence','label']]
Y_test = test['label']
model_lda.fit(X_train, Y_train)


C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [33]:
predict_prob_lda = model_lda.predict_proba(X_test)
print('The class order in the model:')
print(model_lda.classes_)
print('Examples of predicted probablities for the above classes:')
predict_prob_lda[0:5] # inspect the first 5 predictions

The class order in the model:
[0 1]
Examples of predicted probablities for the above classes:


array([[0.08165259, 0.91834741],
       [0.31237413, 0.68762587],
       [0.14363712, 0.85636288],
       [0.17136707, 0.82863293],
       [0.07486996, 0.92513004]])

In [34]:
prediction = np.empty(len(X_test), dtype=object)
prediction = np.where(predict_prob_lda[:, 0]>=0.5, 0, 1)
print(prediction[0:5]) # Inspect the first 5 predictions after labeling.
# Confusion matrix
print(pd.crosstab(prediction, Y_test))
# Accuracy
np.mean(prediction == Y_test)

[1 1 1 1 1]
label    0    1
row_0          
0      119   26
1       60  245


0.8088888888888889

In [7]:
#try to plot LDA
#categories = ['acousticness','danceability','duration', 'loudness','instrumentalness','key','liveness',
#                'mode','speechiness','tempo','time_signature','valence','label']
#lw = 2

#X_r2 = model_lda.fit(X, y).transform(X)

plt.figure()
for color, i, target_name in zip(colors, [0, 1, 2], target_names):
    plt.scatter(X_r2[y == i, 0], X_r2[y == i, 1], alpha=.8, color=color,
                label=target_name)
plt.legend(loc='best', shadow=False, scatterpoints=1)
plt.title('LDA of test dataset')

plt.show()

NameError: name 'X' is not defined

In [35]:
#use of QDA
model_qda = skl_da.QuadraticDiscriminantAnalysis()
model_qda.fit(X_train, Y_train)

C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:692: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

In [37]:
predict_prob_qda = model_qda.predict_proba(X_test)
print('The class order in the model:')
print(model_qda.classes_)
print('Examples of predicted probablities for the above classes:')
predict_prob[0:5] # inspect the first 5 predictions

The class order in the model:
[0 1]
Examples of predicted probablities for the above classes:


C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:716: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))
C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:716: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))
C:\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:719: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.log(s)) for s in self.scalings_])
C:\Anaconda3\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [25]:
prediction = np.empty(len(X_test), dtype=object)
prediction = np.where(predict_prob_qda[:, 0]>=0.5, 0, 1)
print(prediction[0:5]) # Inspect the first 5 predictions after labeling.
# Confusion matrix
print(pd.crosstab(prediction, Y_test))
# Accuracy
np.mean(prediction == Y_test)


[1 1 1 1 1]
label    0    1
row_0          
1      179  271


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater_equal
  


0.6022222222222222